'use strict';
const $=id=>document.getElementById(id);let questions=[], allQuestions=[], filtered=[], current=null, view='question';
const storageKey='ai-fundamentals:all:v2';let progress={};
try{progress=JSON.parse(localStorage.getItem(storageKey)||'{}')||{};const old=JSON.parse(localStorage.getItem('ai-fundamentals:AI-901:v1')||'{}')||{};progress={...old,...progress}}catch{progress={}}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(progress))}catch{}}
function el(tag,props={},children=[]){const node=document.createElement(tag);for(const [key,val] of Object.entries(props)){if(key==='class')node.className=val;else if(key==='text')node.textContent=val;else if(key==='value')node.value=val;else node.setAttribute(key,val)}for(const child of children)node.append(child);return node}
function selected(q){if(['mcq','multiple_select'].includes(q.type))return [...document.querySelectorAll('input[name="option"]:checked')].map(x=>x.value);return [...document.querySelectorAll('[data-answer]')].map(x=>x.value)}
function responseField(choices,index){const s=el('select',{'data-answer':String(index),'aria-label':`Answer ${index+1}`});s.append(el('option',{value:'',text:'Choose an answer'}));for(const choice of choices)s.append(el('option',{value:choice,text:choice}));return s}
function render(){const root=$('content');root.replaceChildren();const done=Object.values(progress);$('score').textContent=`${questions.filter(q=>progress[q.id]).length} / ${questions.length} answered`;$('count').textContent=`${filtered.length} shown`;
 const nav=$('nav');nav.replaceChildren();for(const q of filtered){const b=el('button',{text:String(q.number),class:[progress[q.id]?.correct?'done':progress[q.id]?'wrong':'',q.id===current?'active':'',q.verified?'':'review'].join(' '),'aria-label':`Question ${q.number}${q.verified?'':' requires review'}`});b.onclick=()=>{current=q.id;view='question';render()};nav.append(b)}
 if(view==='results'){resultsView(root);return}let q=questions.find(x=>x.id===current);if(!q||!filtered.some(x=>x.id===q.id)){q=filtered[0];current=q?.id}if(!q){root.append(el('p',{class:'empty',text:'No questions match this filter.'}));return}
 const meta=el('div',{class:'meta'},[el('span',{text:`${q.source} · Question ${q.number} of ${q.source==='AI-900'?323:50}`}),el('span',{class:'pill',text:q.category}),...(!q.verified?[el('span',{class:'pill flag',text:'Review source answer'})]:[])]);root.append(meta,el('h2',{text:q.question||'Use the original question image below.'}));const saved=progress[q.id];
 if(q.source_images?.length){const gallery=el('div',{class:'source-gallery'});const visible=q.type==='source_image_review'&&!saved&&!window.revealed?.[q.id]?[q.prompt_image||q.source_images[0]]:q.type==='source_image_review'?q.source_images:q.source_images.slice(0,1);for(const src of visible)gallery.append(el('img',{src,alt:`${q.source} question ${q.number} source answer area`,loading:'lazy'}));root.append(gallery)}
 if(['mcq','multiple_select'].includes(q.type)){for(const [key,value] of Object.entries(q.options)){const input=el('input',{type:q.type==='mcq'?'radio':'checkbox',name:'option',value:key});input.checked=!!saved?.response.includes(key);input.disabled=!!saved;root.append(el('label',{class:'choice'},[input,el('strong',{text:`${key}. `}),document.createTextNode(value)]))}}
 else if(q.type==='dropdown'){const row=el('div',{class:'row'},[el('label',{text:'Complete the sentence'}),responseField(q.options,0)]);root.append(row);row.querySelector('select').value=saved?.response[0]||''}
 else if(q.type==='yes_no'){const rows=el('div',{class:'rows'});q.statements.forEach((statement,i)=>{const row=el('div',{class:'row'},[el('label',{text:`${i+1}. ${statement}`}),responseField(['Yes','No'],i)]);row.querySelector('select').value=saved?.response[i]||'';rows.append(row)});root.append(rows)}
 else if(q.type==='matching'){const rows=el('div',{class:'rows'});q.targets.forEach((target,i)=>{const row=el('div',{class:'row'},[el('label',{text:target}),responseField(q.choices,i)]);row.querySelector('select').value=saved?.response[i]||'';rows.append(row)});root.append(rows)}
 else if(q.type==='code_select'){root.append(el('pre',{class:'template',text:q.template}));const rows=el('div',{class:'rows'});q.choices.forEach((choices,i)=>{const row=el('div',{class:'row'},[el('label',{text:`Blank ${i+1}`}),responseField(choices,i)]);row.querySelector('select').value=saved?.response[i]||'';rows.append(row)});root.append(rows)}
 if(saved){root.querySelectorAll('select').forEach(x=>x.disabled=true);const box=el('div',{class:`feedback ${saved.correct===null?'manual':saved.correct?'correct':'incorrect'}`},[el('h3',{text:saved.correct===null?'Source answer reviewed':saved.correct?'Correct':'Incorrect'}),...(q.type==='source_image_review'?[]:[el('p',{text:`Correct answer: ${formatAnswer(q)}`})]),el('p',{class:'explain',text:q.explanation||'No explanation supplied in the PDF.'})]);root.append(box)}
 if(!q.verified)root.append(el('p',{class:'review-note',text:`Source review: ${q.review_note}`}));const actions=el('div',{class:'actions'});const left=el('div');const idx=filtered.findIndex(x=>x.id===q.id);for(const [label,offset] of [['Previous',-1],['Next',1]]){const b=el('button',{class:'secondary',text:label});b.disabled=!filtered[idx+offset];b.onclick=()=>{current=filtered[idx+offset].id;view='question';render()};left.append(b)}actions.append(left);if(!saved && q.type==='source_image_review'){if(!window.revealed?.[q.id]){const reveal=el('button',{text:'Reveal source answer'});reveal.onclick=()=>{window.revealed={...window.revealed,[q.id]:true};render()};actions.append(reveal)}else{root.append(el('div',{class:'feedback manual'},[el('h3',{text:'Source answer and explanation'}),el('p',{text:q.explanation})]));for(const [label,correct] of [['I got it right',true],['I got it wrong',false]]){const b=el('button',{class:correct?'':'secondary',text:label});b.onclick=()=>{progress[q.id]={response:[],correct,manual:true};save();render()};actions.append(b)}}}else if(!saved){const submit=el('button',{text:'Submit answer'});submit.onclick=()=>{const response=selected(q);if(response.length!==q.answer.length||response.some(x=>!x)){alert('Please complete every answer before submitting.');return}const correct=response.length===q.answer.length&&response.every((x,i)=>q.type==='multiple_select'?q.answer.includes(x):x===q.answer[i]);progress[q.id]={response,correct};save();render()};actions.append(submit)}root.append(actions)}
function formatAnswer(q){if(q.type==='yes_no')return q.answer.map((x,i)=>`${i+1}: ${x}`).join(' · ');if(q.type==='matching'||q.type==='code_select')return q.answer.map((x,i)=>`${q.type==='matching'?q.targets[i]:`Blank ${i+1}`}: ${x}`).join(' · ');if(q.type==='mcq'||q.type==='multiple_select')return q.answer.map(key=>`${key}. ${q.options[key]}`).join(' · ');return q.answer.join(', ')}
function resultsView(root){root.append(el('h2',{text:'Your results'}));let entries=filtered.map(q=>progress[q.id]);let answered=entries.filter(Boolean).length,correct=entries.filter(x=>x?.correct===true).length;const grid=el('div',{class:'results-grid'});for(const [value,label] of [[answered,'Answered'],[correct,'Correct'],[answered-correct,'Incorrect']])grid.append(el('div',{},[el('strong',{text:String(value)}),el('span',{text:label})]));root.append(grid,el('p',{text:`Showing results for ${filtered.length} questions in the selected category.`}));const list=el('div',{class:'result-list'});for(const q of filtered){const b=el('button',{class:progress[q.id]?.correct?'done':progress[q.id]?'wrong':'',text:`Q${q.number}`});b.onclick=()=>{current=q.id;view='question';render()};list.append(b)}root.append(list)}
function refilter(){const category=$('category').value,term=$('search').value.trim().toLowerCase();filtered=questions.filter(q=>(category==='all'||q.category===category)&&(!term||String(q.number)===term||`${q.question} ${q.id} ${q.category}`.toLowerCase().includes(term)));view='question';render()}
function bankChanged(){const bank=$('bank').value;questions=allQuestions.filter(q=>bank==='both'||q.source===bank);const cats=[...new Set(questions.map(q=>q.category))];const select=$('category');select.replaceChildren(el('option',{value:'all',text:'All Categories'}));for(const cat of cats)select.append(el('option',{value:cat,text:cat}));$('search').value='';current=null;refilter()}
async function init(){try{const [r901,r900]=await Promise.all([fetch('data/ai-901.json'),fetch('data/ai-900.json')]);if(!r901.ok||!r900.ok)throw Error('Question bank JSON missing');allQuestions=[...await r901.json(),...await r900.json()];$('bank').onchange=bankChanged;$('category').onchange=refilter;$('search').oninput=refilter;$('results').onclick=()=>{view='results';render()};$('reset').onclick=()=>{const ids=new Set(questions.map(q=>q.id));if(confirm(`Reset saved progress for ${$('bank').value}?`)){for(const id of ids)delete progress[id];save();render()}};bankChanged()}catch(error){$('content').append(el('p',{class:'empty',text:`Could not load question data (${error.message}). Ensure both JSON files are uploaded to the data folder.`}))}}init();
